apiVersion: clickhouse.altinity.com/v1
kind: ClickHouseInstallation
metadata:
  name: clickhouse
  namespace: clickhouse
spec:
  defaults:
    templates:
      podTemplate: clickhouse-pod
      dataVolumeClaimTemplate: clickhouse-data
      serviceTemplate: clickhouse-service
  configuration:
    users:
      default/networks/ip: "127.0.0.1"
      admin/k8s_secret_password: clickhouse/clickhouse-credentials/password
      admin/networks/ip: "::/0"
      admin/profile: default
      admin/quota: default
    clusters:
      - name: clickhouse
        layout:
          shardsCount: 1
          replicasCount: 1
  templates:
    podTemplates:
      - name: clickhouse-pod
        spec:
          nodeSelector:
            role: stateful
          tolerations:
            - key: role
              value: stateful
              effect: NoSchedule
          containers:
            - name: clickhouse
              image: docker.io/clickhouse/clickhouse-server:latest
    serviceTemplates:
      - name: clickhouse-service
        spec:
          type: NodePort
          ports:
            - name: http
              port: 8123
              nodePort: 30123
            - name: tcp
              port: 9000
              nodePort: 30900
    volumeClaimTemplates:
      - name: clickhouse-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
