apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sftpgo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: sftpgo
  source:
    repoURL: https://github.com/Danavira/data-platform-manifests.git
    targetRevision: HEAD
    path: apps/sftpgo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
