apiVersion: v1
kind: Namespace
metadata:
  name: postgres
  labels:
    postgres-credentials: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: airflow
  labels:
    postgres-credentials: "true"
