apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: marketing-automation
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: marketing-automation
  source:
    repoURL: https://github.com/Danavira/data-platform-manifests.git
    targetRevision: HEAD
    path: apps/marketing-automation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
