apiVersion: v1
kind: Service
metadata:
  name: marketing-automation
  namespace: marketing-automation
spec:
  selector:
    app: marketing-automation
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 31847
