apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres.yaml
  - airflow.yaml
  - minio.yaml
  - clickhouse.yaml
  - clickhouse-operator.yaml
  - monitoring.yaml
  - radar.yaml
  - vikunja.yaml
  - argocd.yaml
  - cert-manager.yaml
  - hello-cicd.yaml
  - cnpg-system.yaml
