apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: postgres
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17

  enableSuperuserAccess: true
  superuserSecret:
    name: postgres-superuser

  seccompProfile:
    type: RuntimeDefault

  bootstrap:
    initdb: {}

  storage:
    size: 10Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  affinity:
    nodeSelector:
      role: stateful
    tolerations:
      - key: role
        operator: Equal
        value: stateful
        effect: NoSchedule
