apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-cicd
  namespace: hello-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-cicd
  template:
    metadata:
      labels:
        app: hello-cicd
    spec:
      containers:
        - name: hello-cicd
          image: ghcr.io/danavira/hello-cicd:6e61511
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "0.1"
              memory: 100Mi
            limits:
              cpu: "0.11"
              memory: 110Mi
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]
      imagePullSecrets:
        - name: ghcr-pull-secret
