image:
  registry: ghcr.io
  repository: clickhouse/clickhouse-server
  tag: latest

shards: 1
replicaCount: 1

nodeSelector:
  role: stateful

tolerations:
  - key: role
    value: stateful
    effect: NoSchedule

persistence:
  size: 10Gi

zookeeper:
  enabled: false

keeper:
  enabled: false
